server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/callog_user?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: callog
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver  # MariaDB도 mysql 드라이버로 접속 가능
    hikari:
      connection-test-query: SELECT 1 # HikariCP 유효성 검사 추가
      validation-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create # 오직 테스트 환경에서만
    generate-ddl: true # 오직 테스트 환경에서만 (spring.jpa.generate-ddl)
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅

